# Generated by Django 5.1.5 on 2025-02-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
